# Site settings
title: programming blog
email: anthonycwu@yahoo.com
description: "Tyring out jekyll and github pages."
baseurl: ""
url: "http://ACWu.github.io"
twitter_username: 
github_username:  ACWu

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
